#for only backend pushes
#When pushed to github
#github action begins CI/CD pipeline
#create a latest docker image
#build new docker image
#login to docker hub
#push docker image
#Login to AWS console
#pull latest docker image in ECR
#replace remote docker image with new docker image
#run docker container in ECS
#manage server with fargate